### ISSUE TITLE
Wrong token?

### ISSUE THREAD

**Issue by driedell** [cncjs/cncjs-pendant-ps3#8]
I'm having trouble getting my controller to move the machine. I was able to install cncjs-pendant-ps3 following your instructions, and I went into the code and uncommented some of the console.log() lines to see what it was doing. I can run the program  just fine over ssh and the pendant appears to connect, but when I manipulate the PS3 controller the machine never reacts.

I noticed that the token shown by cncjs-pendant-ps3 is not the same as the one listed by my cncjs instance. It looks like the text before the first period is identical, but after that they are not the same. 

SSH Output:
```
pi@v1pi:~ $ cncjs-pendant-ps3 -p /dev/input/js0
Waiting for Pendant to connect... please press the PS button on the DS3 controller.
Pendant Connected
connection:change:Not Charging
battery:change:Charging
connection:change:Rumbling
Connected to ws://localhost:8000?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IiIsIm5hbWUiOiJjbmNqcy1wZW5kYW50IiwiaWF0IjoxNTgzMDgzOTkwLCJleHAiOjE1ODU2NzU5OTB9.gcSId2tNqT9-qHNmtgLI54Y-RRPYyPPo7vbcWLGtApM
DPad MOVE: 1.5 : 0 : 0
DPad MOVE: 10 : 0 : 0
DPad MOVE: 0.5 : 0 : 0
DPad MOVE: 10.5 : 0 : 0
DPad MOVE: 0.5 : 0 : 0
DPad MOVE: 10.5 : 0 : 0

```

CNCJS Workspace JSON info:
```
{
  "version": "1.9.20",
  "state": {
    "session": {
      "name": "",
      "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IiIsIm5hbWUiOiIiLCJpYXQiOjE1ODMwODM3NTEsImV4cCI6MTU4NTY3NTc1MX0.kTPiLnss9hQ42cfooCwPJCPvJeaXh6HgTYJmfFbnv5g",
      "enabled": false
    },
```

**Comment by MitchBradley** [comment]
CNCjs generates a new token for each installation.  Have you tried copying the one from the workspace into the pendant?

**Comment by driedell** [comment]
That worked, thanks! I assumed that the pendant was importing the token from the cncjs installation but it looks like it was generating its own token. I just hardcoded my cncjs token into the cncjs-pendant-ps3 code and that worked. When I have time i'll try to figure out how to make it pull the token automatically.
